/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserLayoutRouteImport } from './routes/_userLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as RespondentIndexRouteImport } from './routes/respondent/index'
import { Route as UserLayoutIndexRouteImport } from './routes/_userLayout/index'
import { Route as DashboardDashboardLayoutRouteImport } from './routes/dashboard/_dashboardLayout'
import { Route as UserLayoutProfileRouteImport } from './routes/_userLayout/profile'
import { Route as AuthLayoutAuthSignupRouteImport } from './routes/_authLayout/auth/signup'
import { Route as AuthLayoutAuthLoginRouteImport } from './routes/_authLayout/auth/login'

const UserLayoutRoute = UserLayoutRouteImport.update({
  id: '/_userLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondentIndexRoute = RespondentIndexRouteImport.update({
  id: '/respondent/',
  path: '/respondent/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutIndexRoute = UserLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLayoutRoute,
} as any)
const DashboardDashboardLayoutRoute =
  DashboardDashboardLayoutRouteImport.update({
    id: '/dashboard/_dashboardLayout',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserLayoutProfileRoute = UserLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserLayoutRoute,
} as any)
const AuthLayoutAuthSignupRoute = AuthLayoutAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthLoginRoute = AuthLayoutAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserLayoutIndexRoute
  '/profile': typeof UserLayoutProfileRoute
  '/dashboard': typeof DashboardDashboardLayoutRoute
  '/respondent/': typeof RespondentIndexRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof UserLayoutIndexRoute
  '/profile': typeof UserLayoutProfileRoute
  '/dashboard': typeof DashboardDashboardLayoutRoute
  '/respondent': typeof RespondentIndexRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_userLayout': typeof UserLayoutRouteWithChildren
  '/_userLayout/profile': typeof UserLayoutProfileRoute
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRoute
  '/_userLayout/': typeof UserLayoutIndexRoute
  '/respondent/': typeof RespondentIndexRoute
  '/_authLayout/auth/login': typeof AuthLayoutAuthLoginRoute
  '/_authLayout/auth/signup': typeof AuthLayoutAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/dashboard'
    | '/respondent/'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/dashboard'
    | '/respondent'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_userLayout'
    | '/_userLayout/profile'
    | '/dashboard/_dashboardLayout'
    | '/_userLayout/'
    | '/respondent/'
    | '/_authLayout/auth/login'
    | '/_authLayout/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  UserLayoutRoute: typeof UserLayoutRouteWithChildren
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRoute
  RespondentIndexRoute: typeof RespondentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_userLayout': {
      id: '/_userLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respondent/': {
      id: '/respondent/'
      path: '/respondent'
      fullPath: '/respondent/'
      preLoaderRoute: typeof RespondentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_userLayout/': {
      id: '/_userLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserLayoutIndexRouteImport
      parentRoute: typeof UserLayoutRoute
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_userLayout/profile': {
      id: '/_userLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserLayoutProfileRouteImport
      parentRoute: typeof UserLayoutRoute
    }
    '/_authLayout/auth/signup': {
      id: '/_authLayout/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthLayoutAuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/login': {
      id: '/_authLayout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutAuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuthLoginRoute: typeof AuthLayoutAuthLoginRoute
  AuthLayoutAuthSignupRoute: typeof AuthLayoutAuthSignupRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthLoginRoute: AuthLayoutAuthLoginRoute,
  AuthLayoutAuthSignupRoute: AuthLayoutAuthSignupRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface UserLayoutRouteChildren {
  UserLayoutProfileRoute: typeof UserLayoutProfileRoute
  UserLayoutIndexRoute: typeof UserLayoutIndexRoute
}

const UserLayoutRouteChildren: UserLayoutRouteChildren = {
  UserLayoutProfileRoute: UserLayoutProfileRoute,
  UserLayoutIndexRoute: UserLayoutIndexRoute,
}

const UserLayoutRouteWithChildren = UserLayoutRoute._addFileChildren(
  UserLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  UserLayoutRoute: UserLayoutRouteWithChildren,
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRoute,
  RespondentIndexRoute: RespondentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
