/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserLayoutRouteImport } from './routes/_userLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as RespondentIndexRouteImport } from './routes/respondent/index'
import { Route as DashboardDashboardLayoutRouteImport } from './routes/dashboard/_dashboardLayout'
import { Route as AuthLayoutAuthSignupRouteImport } from './routes/_authLayout/auth/signup'
import { Route as AuthLayoutAuthLoginRouteImport } from './routes/_authLayout/auth/login'

const UserLayoutRoute = UserLayoutRouteImport.update({
  id: '/_userLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondentIndexRoute = RespondentIndexRouteImport.update({
  id: '/respondent/',
  path: '/respondent/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardLayoutRoute =
  DashboardDashboardLayoutRouteImport.update({
    id: '/dashboard/_dashboardLayout',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLayoutAuthSignupRoute = AuthLayoutAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthLoginRoute = AuthLayoutAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserLayoutRoute
  '/dashboard': typeof DashboardDashboardLayoutRoute
  '/respondent/': typeof RespondentIndexRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof UserLayoutRoute
  '/dashboard': typeof DashboardDashboardLayoutRoute
  '/respondent': typeof RespondentIndexRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_userLayout': typeof UserLayoutRoute
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRoute
  '/respondent/': typeof RespondentIndexRoute
  '/_authLayout/auth/login': typeof AuthLayoutAuthLoginRoute
  '/_authLayout/auth/signup': typeof AuthLayoutAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/respondent/'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/respondent' | '/auth/login' | '/auth/signup'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_userLayout'
    | '/dashboard/_dashboardLayout'
    | '/respondent/'
    | '/_authLayout/auth/login'
    | '/_authLayout/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  UserLayoutRoute: typeof UserLayoutRoute
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRoute
  RespondentIndexRoute: typeof RespondentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_userLayout': {
      id: '/_userLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respondent/': {
      id: '/respondent/'
      path: '/respondent'
      fullPath: '/respondent/'
      preLoaderRoute: typeof RespondentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/auth/signup': {
      id: '/_authLayout/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthLayoutAuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/login': {
      id: '/_authLayout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutAuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuthLoginRoute: typeof AuthLayoutAuthLoginRoute
  AuthLayoutAuthSignupRoute: typeof AuthLayoutAuthSignupRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthLoginRoute: AuthLayoutAuthLoginRoute,
  AuthLayoutAuthSignupRoute: AuthLayoutAuthSignupRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  UserLayoutRoute: UserLayoutRoute,
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRoute,
  RespondentIndexRoute: RespondentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
