/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserLayoutRouteImport } from './routes/_userLayout'
import { Route as DashboardDashboardLayoutRouteImport } from './routes/dashboard/_dashboardLayout'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_authLayout'
import { Route as AuthSignUpPageRouteImport } from './routes/auth/SignUpPage'
import { Route as AuthLoginPageRouteImport } from './routes/auth/LoginPage'

const UserLayoutRoute = UserLayoutRouteImport.update({
  id: '/_userLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardLayoutRoute =
  DashboardDashboardLayoutRouteImport.update({
    id: '/dashboard/_dashboardLayout',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/auth/_authLayout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpPageRoute = AuthSignUpPageRouteImport.update({
  id: '/auth/SignUpPage',
  path: '/auth/SignUpPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/auth/LoginPage',
  path: '/auth/LoginPage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserLayoutRoute
  '/auth/LoginPage': typeof AuthLoginPageRoute
  '/auth/SignUpPage': typeof AuthSignUpPageRoute
  '/auth': typeof AuthAuthLayoutRoute
  '/dashboard': typeof DashboardDashboardLayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof UserLayoutRoute
  '/auth/LoginPage': typeof AuthLoginPageRoute
  '/auth/SignUpPage': typeof AuthSignUpPageRoute
  '/auth': typeof AuthAuthLayoutRoute
  '/dashboard': typeof DashboardDashboardLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_userLayout': typeof UserLayoutRoute
  '/auth/LoginPage': typeof AuthLoginPageRoute
  '/auth/SignUpPage': typeof AuthSignUpPageRoute
  '/auth/_authLayout': typeof AuthAuthLayoutRoute
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/LoginPage'
    | '/auth/SignUpPage'
    | '/auth'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/LoginPage' | '/auth/SignUpPage' | '/auth' | '/dashboard'
  id:
    | '__root__'
    | '/_userLayout'
    | '/auth/LoginPage'
    | '/auth/SignUpPage'
    | '/auth/_authLayout'
    | '/dashboard/_dashboardLayout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserLayoutRoute: typeof UserLayoutRoute
  AuthLoginPageRoute: typeof AuthLoginPageRoute
  AuthSignUpPageRoute: typeof AuthSignUpPageRoute
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRoute
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_userLayout': {
      id: '/_userLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/SignUpPage': {
      id: '/auth/SignUpPage'
      path: '/auth/SignUpPage'
      fullPath: '/auth/SignUpPage'
      preLoaderRoute: typeof AuthSignUpPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/LoginPage': {
      id: '/auth/LoginPage'
      path: '/auth/LoginPage'
      fullPath: '/auth/LoginPage'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  UserLayoutRoute: UserLayoutRoute,
  AuthLoginPageRoute: AuthLoginPageRoute,
  AuthSignUpPageRoute: AuthSignUpPageRoute,
  AuthAuthLayoutRoute: AuthAuthLayoutRoute,
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
